#include "Constants.hpp"

#include "nlohmann/json.hpp"

/** A JSON key and value corresponding to a game constant. */
#define FIELD_TO_JSON(x) {#x, constants.x}

/** Get a field from JSON. */
#define FIELD_FROM_JSON(x) json.at(#x)

namespace hlt {

/**
 * Encode the constants to JSON.
 * @param[out] json The JSON output.
 * @param constants The constants.
 */
void to_json(nlohmann::json &json, const Constants &constants) {
    json = {
            FIELD_TO_JSON(STRICT_ERRORS),

            FIELD_TO_JSON(MAX_PLAYERS),

            FIELD_TO_JSON(DEFAULT_MAP_WIDTH),
            FIELD_TO_JSON(DEFAULT_MAP_HEIGHT),
            FIELD_TO_JSON(MAX_CELL_PRODUCTION),
            FIELD_TO_JSON(MIN_CELL_PRODUCTION),

            FIELD_TO_JSON(MAX_ENERGY),
            FIELD_TO_JSON(NEW_ENTITY_ENERGY_COST),
            FIELD_TO_JSON(INITIAL_ENERGY),

            FIELD_TO_JSON(DROPOFF_COST),
            FIELD_TO_JSON(MOVE_COST_RATIO),
            FIELD_TO_JSON(DROPOFF_PENALTY_RATIO),
            FIELD_TO_JSON(EXTRACT_RATIO),

            FIELD_TO_JSON(PERSISTENCE),
            FIELD_TO_JSON(FACTOR_EXP_1),
            FIELD_TO_JSON(FACTOR_EXP_2),

            FIELD_TO_JSON(MIN_TURNS),
            FIELD_TO_JSON(MIN_TURN_THRESHOLD),
            FIELD_TO_JSON(MAX_TURNS),
            FIELD_TO_JSON(MAX_TURN_THRESHOLD),

            FIELD_TO_JSON(CAPTURE_ENABLED),
            FIELD_TO_JSON(CAPTURE_RADIUS),
            FIELD_TO_JSON(SHIPS_ABOVE_FOR_CAPTURE),

            FIELD_TO_JSON(INSPIRATION_ENABLED),
            FIELD_TO_JSON(INSPIRED_EXTRACT_RATIO),
            FIELD_TO_JSON(INSPIRED_BONUS_MULTIPLIER),
            FIELD_TO_JSON(INSPIRED_MOVE_COST_RATIO),
            FIELD_TO_JSON(INSPIRATION_RADIUS),
            FIELD_TO_JSON(INSPIRATION_SHIP_COUNT),

            FIELD_TO_JSON(INITIAL_HP),
            FIELD_TO_JSON(ATTACK_HP_DAMAGE),
            FIELD_TO_JSON(ATTACK_HP_SELF_DAMAGE),
            FIELD_TO_JSON(ATTACK_HALITE_STEAL_RATIO),
            FIELD_TO_JSON(HEAL_AMOUNT),
            FIELD_TO_JSON(DEFEND_RETALIATION_DAMAGE),
            FIELD_TO_JSON(DEFEND_ALLOWS_MINING),
            FIELD_TO_JSON(ENABLE_COMBAT_COMMANDS),
            FIELD_TO_JSON(COLLISION_HP_DAMAGE),
            FIELD_TO_JSON(RULESET_VERSION),
            FIELD_TO_JSON(ENABLE_ATTACKER_SELF_DAMAGE),
            FIELD_TO_JSON(KILL_CREDIT_TO_ATTACKER),
            FIELD_TO_JSON(KILL_HALITE_BONUS_RATIO),
            FIELD_TO_JSON(ATTACK_RANGE),
            FIELD_TO_JSON(SPAWN_COST_GROWTH),
            FIELD_TO_JSON(DROPOFF_COST_GROWTH),
            FIELD_TO_JSON(EMERGENCY_SPAWN_ENABLED),
            FIELD_TO_JSON(EMERGENCY_SPAWN_PERIOD),
            FIELD_TO_JSON(EMERGENCY_SPAWN_COUNT),
            FIELD_TO_JSON(EMERGENCY_HALITE_BONUS),
            FIELD_TO_JSON(EMERGENCY_PROTECTION_TURNS),
            FIELD_TO_JSON(HALITE_REBALANCE_ENABLED),
            FIELD_TO_JSON(HALITE_REBALANCE_PERIOD),
            FIELD_TO_JSON(HALITE_REBALANCE_FRACTION),
            FIELD_TO_JSON(HALITE_REBALANCE_MIN_GAP_FRAC),
            FIELD_TO_JSON(OVER_SHIP_TAX_THRESHOLD),
            FIELD_TO_JSON(OVER_SHIP_TAX_PER_TURN),
            FIELD_TO_JSON(SHIP_INCOME_PER_TURN),
            FIELD_TO_JSON(SHIP_COUNT_TARGET),
            FIELD_TO_JSON(SHIP_COUNT_DEVIATION_PENALTY),
            FIELD_TO_JSON(SPAWN_QUAD_THRESHOLD),
            FIELD_TO_JSON(SPAWN_QUAD_GROWTH),
            FIELD_TO_JSON(MINING_INTERFERENCE_RANGE),
            FIELD_TO_JSON(MINING_INTERFERENCE_RATIO),
            FIELD_TO_JSON(MINING_INTERFERENCE_CARGO_LOSS_RATIO),
            FIELD_TO_JSON(PLUNDER_RANGE),
            FIELD_TO_JSON(PLUNDER_HALITE_PER_TURN),
            FIELD_TO_JSON(CELL_REGEN_ENABLED),
            FIELD_TO_JSON(CELL_REGEN_RATE),
            FIELD_TO_JSON(CELL_REGEN_CAP_FRACTION)
    };
}

/**
 * Decode the constants from JSON.
 * @param json The JSON input.
 * @param[out] constants The decoded constants.
 */
// Helper to read a required field (throws if missing, consistent with original behaviour)
#define FROM_JSON_REQ(field) constants.field = json.at(#field).get<decltype(constants.field)>()
// Helper to read an optional field (keeps current value as default)
#define FROM_JSON_OPT(field) if (json.count(#field)) constants.field = json.at(#field).get<decltype(constants.field)>()

void from_json(const nlohmann::json &json, Constants &constants) {
    // All fields are optional: in-class defaults apply for any field absent from
    // the JSON.  This lets -c accept partial override files (e.g. a single key)
    // while remaining fully compatible with complete constants JSON dumps.
    FROM_JSON_OPT(STRICT_ERRORS);
    FROM_JSON_OPT(MAX_PLAYERS);
    FROM_JSON_OPT(DEFAULT_MAP_WIDTH);
    FROM_JSON_OPT(DEFAULT_MAP_HEIGHT);
    FROM_JSON_OPT(MAX_CELL_PRODUCTION);
    FROM_JSON_OPT(MIN_CELL_PRODUCTION);
    FROM_JSON_OPT(MAX_ENERGY);
    FROM_JSON_OPT(NEW_ENTITY_ENERGY_COST);
    FROM_JSON_OPT(INITIAL_ENERGY);
    FROM_JSON_OPT(DROPOFF_COST);
    FROM_JSON_OPT(INITIAL_DROPOFF_HALITE);
    FROM_JSON_OPT(INITIAL_FACTORY_HALITE);
    FROM_JSON_OPT(MOVE_COST_RATIO);
    FROM_JSON_OPT(DROPOFF_PENALTY_RATIO);
    FROM_JSON_OPT(EXTRACT_RATIO);
    FROM_JSON_OPT(PERSISTENCE);
    FROM_JSON_OPT(FACTOR_EXP_1);
    FROM_JSON_OPT(FACTOR_EXP_2);
    FROM_JSON_OPT(MIN_TURNS);
    FROM_JSON_OPT(MIN_TURN_THRESHOLD);
    FROM_JSON_OPT(MAX_TURNS);
    FROM_JSON_OPT(MAX_TURN_THRESHOLD);
    FROM_JSON_OPT(CAPTURE_ENABLED);
    FROM_JSON_OPT(CAPTURE_RADIUS);
    FROM_JSON_OPT(SHIPS_ABOVE_FOR_CAPTURE);
    FROM_JSON_OPT(INSPIRATION_ENABLED);
    FROM_JSON_OPT(INSPIRED_EXTRACT_RATIO);
    FROM_JSON_OPT(INSPIRED_BONUS_MULTIPLIER);
    FROM_JSON_OPT(INSPIRED_MOVE_COST_RATIO);
    FROM_JSON_OPT(INSPIRATION_RADIUS);
    FROM_JSON_OPT(INSPIRATION_SHIP_COUNT);
    FROM_JSON_OPT(INITIAL_HP);
    FROM_JSON_OPT(ATTACK_HP_DAMAGE);
    FROM_JSON_OPT(ATTACK_HP_SELF_DAMAGE);
    FROM_JSON_OPT(ATTACK_HALITE_STEAL_RATIO);
    FROM_JSON_OPT(HEAL_AMOUNT);
    FROM_JSON_OPT(DEFEND_RETALIATION_DAMAGE);
    FROM_JSON_OPT(DEFEND_ALLOWS_MINING);
    FROM_JSON_OPT(ENABLE_COMBAT_COMMANDS);
    FROM_JSON_OPT(COLLISION_HP_DAMAGE);
    FROM_JSON_OPT(RULESET_VERSION);
    FROM_JSON_OPT(ENABLE_ATTACKER_SELF_DAMAGE);
    FROM_JSON_OPT(KILL_CREDIT_TO_ATTACKER);
    FROM_JSON_OPT(KILL_HALITE_BONUS_RATIO);
    FROM_JSON_OPT(ATTACK_RANGE);
    FROM_JSON_OPT(SPAWN_COST_GROWTH);
    FROM_JSON_OPT(DROPOFF_COST_GROWTH);
    FROM_JSON_OPT(EMERGENCY_SPAWN_ENABLED);
    FROM_JSON_OPT(EMERGENCY_SPAWN_PERIOD);
    FROM_JSON_OPT(EMERGENCY_SPAWN_COUNT);
    FROM_JSON_OPT(EMERGENCY_HALITE_BONUS);
    FROM_JSON_OPT(EMERGENCY_PROTECTION_TURNS);
    FROM_JSON_OPT(HALITE_REBALANCE_ENABLED);
    FROM_JSON_OPT(HALITE_REBALANCE_PERIOD);
    FROM_JSON_OPT(HALITE_REBALANCE_FRACTION);
    FROM_JSON_OPT(HALITE_REBALANCE_MIN_GAP_FRAC);
    FROM_JSON_OPT(OVER_SHIP_TAX_THRESHOLD);
    FROM_JSON_OPT(OVER_SHIP_TAX_PER_TURN);
    FROM_JSON_OPT(SHIP_INCOME_PER_TURN);
    FROM_JSON_OPT(SHIP_COUNT_TARGET);
    FROM_JSON_OPT(SHIP_COUNT_DEVIATION_PENALTY);
    FROM_JSON_OPT(SPAWN_QUAD_THRESHOLD);
    FROM_JSON_OPT(SPAWN_QUAD_GROWTH);
    FROM_JSON_OPT(MINING_INTERFERENCE_RANGE);
    FROM_JSON_OPT(MINING_INTERFERENCE_RATIO);
    FROM_JSON_OPT(MINING_INTERFERENCE_CARGO_LOSS_RATIO);
    FROM_JSON_OPT(PLUNDER_RANGE);
    FROM_JSON_OPT(PLUNDER_HALITE_PER_TURN);
    FROM_JSON_OPT(CELL_REGEN_ENABLED);
    FROM_JSON_OPT(CELL_REGEN_RATE);
    FROM_JSON_OPT(CELL_REGEN_CAP_FRACTION);
}

}
